http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "rs-estates:$apr1$QwErTyUi$9z8x7w6v5u4t3r2q1p0oM/"
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
