http:
  middlewares:
    auth:
      basicAuth:
        users:
          - "rs-estates:$apr1$10hVrsSV$eQiBK2vdN0w3oZFTO6eUU/"
    redirect-to-https:
      redirectScheme:
        scheme: https
        permanent: true
    rate-limit:
      rateLimit:
        average: 100
        burst: 50
